# -*- coding: utf-8 -*-
"""MLT Week_2_programming.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cs2E4UTWBt2YEMCcVQ_jWvvWlhDXRotZ
"""

import numpy as np
import matplotlib.pyplot as plt

"""# Week-2

**Note to Learners**:

- For questions that involve plotting, just enter $0$ as the answer in the portal.
- For numerical questions, there are two parts. The first part expects you to compute some quantity, say a parameter of a machine learning model. The second part will require you to convert this quantity (if it is not a scalar) into a scalar so that it can be entered as the answer on the portal to the corresponding NAT question.

## Dataset

Run the cell given below to generate the data-matrix $\mathbf{X}$, which is of shape $(n, d)$, where $n$ denotes the number of samples and $d$ denotes the number of features. Ignore the vector $y$. You will be using this dataset for the rest of the assignment. Do not edit this cell.
"""

from sklearn.datasets import make_circles

X, y = make_circles(n_samples=1000, factor=0.9, noise=0.2, random_state=0)

"""## Problem 1
Plot the dataset using matplotlib.
"""

import matplotlib.pyplot as plt
plt.figure(figsize=(8, 8))
plt.scatter(X[:, 0], X[:, 1], c=y, cmap='viridis', s=50, alpha=0.7)
plt.title('Generated Circles Dataset')
plt.xlabel('Feature 1')
plt.ylabel('Feature 2')
plt.grid(True, linestyle='--', alpha=0.6)
plt.show()

"""## Problem 2
How many samples are there in the dataset?

"""

num_samples = X.shape[0]
print(f"There are {num_samples} samples in the dataset.")

"""## Problem 3
How many features are there in the dataset?
"""

num_features = X.shape[1]
print(f"There are {num_features} features in the dataset.")

"""## Problem 4
Find the kernel matrix $K$ using the polynomial kernel with degree $2$.

<u>Conversion</u>

Enter the following quantity as your answer correct to two decimal places:

$$
\cfrac{1}{n} \sqrt{\sum \limits_{i = 1}^{n} \sum \limits_{j = 1}^{n} (K_{ij})^2}
$$
"""

import numpy as np

n_samples = X.shape[0]

# Calculate the polynomial kernel matrix with degree 2
def polynomial_kernel(X1, X2, degree=2, c=1):
    return (np.dot(X1, X2.T) + c) ** degree

K_poly = polynomial_kernel(X, X, degree=2, c=1)

# Calculate the conversion quantity
conversion_quantity = (1 / n_samples) * np.sqrt(np.sum(K_poly**2))

print(f"The polynomial kernel matrix K (degree 2) has been calculated.")
print(f"Conversion quantity: {conversion_quantity:.3f}")

"""## Problem 5
Find the kernel matrix $K$ using the Gaussian kernel with parameter $\sigma = 2$.

<u>Conversion</u>

Enter the following quantity as your answer correct to two decimal places:

$$
\cfrac{1}{n} \sqrt{\sum \limits_{i = 1}^{n} \sum \limits_{j = 1}^{n} (K_{ij})^2}
$$
"""

import numpy as np

n_samples = X.shape[0]
sigma = 2.0

# Calculate the Gaussian kernel matrix with sigma = 2
def gaussian_kernel(X1, X2, sigma):
    K = np.zeros((X1.shape[0], X2.shape[0]))
    for i in range(X1.shape[0]):
        for j in range(X2.shape[0]):
            K[i, j] = np.exp(-np.linalg.norm(X1[i] - X2[j])**2 / (2 * sigma**2))
    return K

K_gaussian = gaussian_kernel(X, X, sigma)

# Calculate the conversion quantity
conversion_quantity_gaussian = (1 / n_samples) * np.sqrt(np.sum(K_gaussian**2))

print(f"The Gaussian kernel matrix K (sigma = {sigma}) has been calculated.")
print(f"Conversion quantity: {conversion_quantity_gaussian:.3f}")

"""## Problem 6
Find the center of the kernel matrix $K$ obtained in problem 2. Call this centered matrix $KC$.

<u>Conversion</u>

Enter the following quantity as your answer correct to two decimal places:

$$
\cfrac{1}{n} \sqrt{\sum \limits_{i = 1}^{n} \sum \limits_{j = 1}^{n} KC_{ij}^2}
$$
"""

import numpy as np

n = n_samples # Renaming for clarity as per formula

# Calculate the centering matrix H
I = np.identity(n)
ones_vector = np.ones((n, 1))
H = I - (1 / n) * np.dot(ones_vector, ones_vector.T)

# Calculate the centered kernel matrix KC
KC = np.dot(np.dot(H, K_poly), H)

# Calculate the conversion quantity
conversion_quantity_kc = (1 / n) * np.sqrt(np.sum(KC**2))

print("The centered kernel matrix KC has been calculated.")
print(f"Conversion quantity: {conversion_quantity_kc:.3f}")

"""## Problem 7
Find the projections (scalar) of all the data points on to the first two principal components obtained using polynomial kernel of degree 2.

<u>Conversion</u>

if $\alpha_1, \alpha_2, ..., \alpha_n$ are the prjections on the first PC and $\beta_1, \beta_2, ..., \beta_n$ are the projections on the second PC, enter the following quantity as your answer correct to two decimal places:

$$\sum_{i = 1}^{n} \alpha_i + \sum_{i = 1}^{n} \beta_i$$
"""

import numpy as np

# Perform eigen-decomposition on the centered kernel matrix KC
eigenvalues, eigenvectors = np.linalg.eigh(KC)

# Sort eigenvalues and eigenvectors in descending order
sorted_indices = np.argsort(eigenvalues)[::-1]
eigenvalues = eigenvalues[sorted_indices]
eigenvectors = eigenvectors[:, sorted_indices]

# Select the first two principal components (eigenvectors)
# Ensure eigenvalues are positive before taking sqrt
# Handle potential small negative eigenvalues due to numerical precision by setting them to 0

top_eigenvalues = eigenvalues[:2]
top_eigenvectors = eigenvectors[:, :2]

# Normalize the eigenvectors to get the principal components (alpha vectors)
# Only consider positive eigenvalues for normalization

alphas = np.zeros_like(top_eigenvectors)
for i in range(2):
    if top_eigenvalues[i] > 1e-9:  # Check if eigenvalue is significantly positive
        alphas[:, i] = top_eigenvectors[:, i] / np.sqrt(top_eigenvalues[i])
    else:
        # If eigenvalue is zero or negative, set corresponding alpha to zero
        alphas[:, i] = np.zeros_like(top_eigenvectors[:, i])

# Calculate the projections of the data points onto the first two principal components
# Projections are KC @ alpha (where alpha are the normalized eigenvectors)

# First principal component projections (alpha_1)
projections_pc1 = np.dot(KC, alphas[:, 0])

# Second principal component projections (alpha_2)
projections_pc2 = np.dot(KC, alphas[:, 1])

# Calculate the conversion quantity: sum of projections on PC1 + sum of projections on PC2
conversion_quantity_projections = np.sum(projections_pc1) + np.sum(projections_pc2)

print(f"Sum of projections on the first principal component: {np.sum(projections_pc1):.3f}")
print(f"Sum of projections on the second principal component: {np.sum(projections_pc2):.3f}")
print(f"Conversion quantity (sum of all projections): {conversion_quantity_projections:.2f}")

